name: rainbow_color
description: Simplified multi-color interpolation. Map a numerical domain to a smooth-transitioning color range.
version: 2.0.1
homepage: https://github.com/ilikerobots/rainbow_color

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  rainbow_vis: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

